# Generated by Django 5.2.8 on 2026-02-11 22:09

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sensor_images/'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='water_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
