# Generated by Django 6.0.1 on 2026-02-19 22:43

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_sensorreading_image_sensorreading_water_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorreading",
            name="gas",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
