# Generated by Django 6.0.1 on 2026-02-19 22:44

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_sensorreading_gas_alter_sensorreading_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorreading",
            name="gas",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="humidity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="light",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="temperature",
            field=models.FloatField(default=0.0),
        ),
    ]
