# Generated by Django 5.2.8 on 2026-02-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_systemlog_alter_sensorreading_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
