# Generated by Django 5.2.8 on 2026-03-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_userprofile_device_id_sensorreading_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaredevice',
            name='name',
            field=models.CharField(blank=True, help_text='Custom name or location', max_length=100, null=True),
        ),
    ]
