# Generated by Django 5.2.11 on 2026-03-30 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_hardwaredevice_id_alter_sensorreading_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Seedling (Free)'), ('PRO', 'Harvest (Pro - $9/mo)'), ('ENT', 'Plantation (Enterprise)')], default='FREE', max_length=10)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('max_devices', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
