# Generated by Django 4.2.30 on 2026-05-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_hardwaredevice_id_alter_sensorreading_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Seedling (Free)'), ('PRO', 'Harvest (Pro - $100/mo)'), ('ENT', 'Plantation (Enterprise - $209/mo)')], default='FREE', max_length=10),
        ),
    ]
