# Generated by Django 5.2.17 on 2026-08-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_scope_system_logs_to_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.CharField(choices=[('STD', 'Standard'), ('RES', 'Researcher'), ('PRM', 'Premium')], default='STD', max_length=10),
        ),
    ]
